#!/usr/bin/env python3
"""
DevContext CLI — AI-Ready Codebase Context Generator

Usage:
    devcontext generate <path> [--output FILE] [--format json|md]
    devcontext --version
"""

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="devcontext",
        description="Generate AI-ready context from your codebase",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    gen = sub.add_parser("generate", help="Generate context from codebase")
    gen.add_argument("path", type=Path, help="Path to codebase directory")
    gen.add_argument("--output", "-o", type=Path, help="Output file (default: stdout)")
    gen.add_argument(
        "--format", "-f", choices=["json", "md"], default="json",
        help="Output format (default: json)"
    )

    sub.add_parser("--version", help="Show version").add_argument(
        "--version", action="store_true"
    )

    return parser.parse_args()


def get_file_tree(root: Path, max_depth: int = 4) -> list[dict[str, Any]]:
    """Build a tree representation of the project structure."""
    tree = []
    
    # Common directories to skip
    skip_dirs = {'.git', '__pycache__', 'node_modules', '.venv', 'venv', 
                 '.pytest_cache', '.mypy_cache', 'dist', 'build', '.tox',
                 '.idea', '.vscode', 'vendor', 'target'}

    # Common file extensions to include
    code_exts = {'.py', '.js', '.ts', '.jsx', '.tsx', '.go', '.rs', '.java',
                 '.c', '.cpp', '.h', '.hpp', '.cs', '.rb', '.php', '.swift',
                 '.kt', '.scala', '.vue', '.svelte', '.md', '.yaml', '.yml',
                 '.json', '.toml', '.txt', '.sh', '.bash', '.zsh', '.fish'}
    
    skip_files = {'package-lock.json', 'yarn.lock', 'poetry.lock', 
                  'Pipfile.lock', 'requirements.txt', '.gitignore'}

    def walk(path: Path, depth: int = 0):
        if depth > max_depth:
            return
        
        try:
            for item in sorted(path.iterdir()):
                # Skip hidden and common non-source dirs
                if item.name.startswith('.') and item.name not in {'.gitignore', '.env.example'}:
                    continue
                if item.name in skip_dirs:
                    continue
                if item.name in skip_files:
                    continue
                    
                if item.is_file():
                    ext = item.suffix.lower()
                    if ext in code_exts or item.name in ['Makefile', 'Dockerfile', 'docker-compose.yml']:
                        rel = item.relative_to(root)
                        size = item.stat().st_size
                        tree.append({
                            "path": str(rel),
                            "type": "file",
                            "size": size
                        })
                elif item.is_dir():
                    tree.append({
                        "path": str(item.relative_to(root)) + "/",
                        "type": "dir"
                    })
                    walk(item, depth + 1)
        except PermissionError:
            pass

    walk(root)
    return tree


def extract_key_content(root: Path) -> list[dict[str, Any]]:
    """Extract key content from important files."""
    content = []
    
    # Files to read fully
    key_files = {
        'README.md': 'readme',
        'pyproject.toml': 'config',
        'setup.py': 'config',
        'package.json': 'config',
        'Cargo.toml': 'config',
        'go.mod': 'config',
        'requirements.txt': 'deps',
        'Dockerfile': 'docker',
        'docker-compose.yml': 'docker',
        'Makefile': 'makefile',
    }
    
    for fname, ftype in key_files.items():
        fpath = root / fname
        if fpath.exists() and fpath.is_file():
            try:
                text = fpath.read_text(encoding='utf-8', errors='replace')[:3000]
                content.append({
                    "file": fname,
                    "type": ftype,
                    "preview": text
                })
            except Exception:
                pass
    
    return content


def generate_context(root: Path) -> dict[str, Any]:
    """Generate full context for a codebase."""
    return {
        "tool": "DevContext",
        "version": "0.1.0",
        "root": str(root),
        "file_tree": get_file_tree(root),
        "key_content": extract_key_content(root),
        "summary": {
            "total_files": len([f for f in get_file_tree(root) if f["type"] == "file"])
        }
    }


def format_markdown(ctx: dict[str, Any]) -> str:
    """Format context as readable Markdown."""
    lines = [
        "# Codebase Context",
        "",
        f"**Generated by DevContext v{ctx['version']}**",
        f"**Root:** `{ctx['root']}`",
        "",
        "## File Tree",
        ""
    ]
    
    for item in ctx['file_tree']:
        if item['type'] == 'dir':
            lines.append(f"📁 `{item['path']}`")
        else:
            lines.append(f"📄 `{item['path']}` ({item['size']} bytes)")
    
    if ctx.get('key_content'):
        lines.extend(["", "## Key Files", ""])
        for item in ctx['key_content']:
            lines.extend([f"### `{item['file']}`", "", f"```{item['type']}", item['preview'][:500], "```", ""])
    
    return "\n".join(lines)


def main():
    args = parse_args()
    
    if args.command == "--version":
        print("DevContext v0.1.0")
        return
    
    if args.command == "generate":
        if not args.path.exists():
            print(f"Error: Path not found: {args.path}", file=sys.stderr)
            sys.exit(1)
        
        ctx = generate_context(args.path)
        
        if args.format == "md":
            output = format_markdown(ctx)
        else:
            output = json.dumps(ctx, indent=2)
        
        if args.output:
            args.output.write_text(output)
            print(f"✅ Context saved to {args.output}")
        else:
            print(output)


if __name__ == "__main__":
    main()