# Export functionality for DevContext

import json
import base64
from pathlib import Path
from typing import Dict, Any, Optional


def export_to_markdown(context: Dict[str, Any]) -> str:
    """Export context as formatted Markdown."""
    lines = ["# Codebase Context", ""]
    
    # Header
    if context.get("version"):
        lines.append(f"*Generated by DevContext v{context['version']}*")
    if context.get("generated"):
        lines.append(f"*Generated: {context['generated']}*")
    lines.append("")
    
    # Summary stats
    meta = context.get("metadata", {})
    if meta:
        lines.append("## Summary")
        if meta.get("total_files"):
            lines.append(f"- **Total files:** {meta['total_files']}")
        if meta.get("languages"):
            langs = ", ".join(meta["languages"])
            lines.append(f"- **Languages:** {langs}")
        if meta.get("total_functions"):
            lines.append(f"- **Functions:** {meta['total_functions']}")
        if meta.get("total_classes"):
            lines.append(f"- **Classes:** {meta['total_classes']}")
        lines.append("")
    
    # Files
    files = context.get("files", {})
    if files:
        lines.append("## Files")
        for path, info in sorted(files.items()):
            lines.append(f"### `{path}`")
            if isinstance(info, dict):
                if info.get("language"):
                    lines.append(f"*Language: {info['language']}*")
                if info.get("functions"):
                    lines.append(f"*Functions: {len(info['functions'])}*")
                if info.get("classes"):
                    lines.append(f"*Classes: {len(info['classes'])}*")
                if info.get("exports"):
                    lines.append(f"*Exports: {', '.join(info['exports'])}*")
            lines.append("")
    
    return "\n".join(lines)


def export_to_html(context: Dict[str, Any], title: str = "Codebase Context") -> str:
    """Export context as HTML page."""
    md_content = export_to_markdown(context)
    
    # Simple markdown-to-HTML conversion
    html = md_content
    html = html.replace("# ", "<h1>").replace("\n", "</h1>\n", 1)
    html = html.replace("## ", "<h2>").replace("\n## ", "</h2>\n<h2>")
    html = html.replace("### ", "<h3>").replace("\n### ", "</h3>\n<h3>")
    html = html.replace("**", "<strong>").replace("**", "</strong>")
    html = html.replace("*", "<em>").replace("*", "</em>")
    html = html.replace("`", "<code>").replace("`", "</code>")
    html = html.replace("- ", "<li>").replace("\n- ", "</li>\n<li>")
    
    return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{title}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
               max-width: 900px; margin: 0 auto; padding: 2rem; }}
        code {{ background: #f4f4f4; padding: 0.2rem 0.4rem; border-radius: 3px; }}
        pre {{ background: #f4f4f4; padding: 1rem; overflow-x: auto; }}
        h1, h2, h3 {{ color: #333; }}
    </style>
</head>
<body>
{html}
</body>
</html>"""


def export_to_txt(context: Dict[str, Any]) -> str:
    """Export context as plain text."""
    lines = ["DEVCONTEXT - CODEBASE CONTEXT", "=" * 40, ""]
    
    meta = context.get("metadata", {})
    if meta:
        lines.append("SUMMARY:")
        for k, v in meta.items():
            lines.append(f"  {k}: {v}")
        lines.append("")
    
    files = context.get("files", {})
    if files:
        lines.append("FILES:")
        for path in sorted(files.keys()):
            lines.append(f"  {path}")
        lines.append("")
    
    return "\n".join(lines)


def export_to_pdf_ready(context: Dict[str, Any]) -> str:
    """Export context in a format optimized for PDF conversion."""
    md = export_to_markdown(context)
    # Add page breaks
    md = md.replace("## ", "\n---\n## ")
    return md


def export_to_gist(context: Dict[str, Any], filename: str = "context.json") -> Dict[str, Any]:
    """Prepare context for GitHub Gist export."""
    return {
        "filename": filename,
        "content": json.dumps(context, indent=2),
        "public": False
    }


def export_bundle(context: Dict[str, Any], formats: list = None) -> Dict[str, str]:
    """Export context in multiple formats at once."""
    if formats is None:
        formats = ["json", "markdown"]
    
    bundle = {}
    
    if "json" in formats:
        bundle["json"] = json.dumps(context, indent=2)
    if "markdown" in formats:
        bundle["markdown"] = export_to_markdown(context)
    if "html" in formats:
        bundle["html"] = export_to_html(context)
    if "txt" in formats:
        bundle["txt"] = export_to_txt(context)
    
    return bundle


# CLI integration
def main():
    import argparse
    parser = argparse.ArgumentParser(description="Export DevContext output")
    parser.add_argument("input", help="Input context JSON file")
    parser.add_argument("-f", "--format", choices=["json", "md", "html", "txt"],
                        default="md", help="Output format")
    parser.add_argument("-o", "--output", help="Output file (default: stdout)")
    
    args = parser.parse_args()
    
    with open(args.input) as f:
        context = json.load(f)
    
    if args.format == "json":
        output = json.dumps(context, indent=2)
    elif args.format == "md":
        output = export_to_markdown(context)
    elif args.format == "html":
        output = export_to_html(context)
    else:
        output = export_to_txt(context)
    
    if args.output:
        with open(args.output, 'w') as f:
            f.write(output)
        print(f"Exported to {args.output}")
    else:
        print(output)


if __name__ == "__main__":
    main()