"""Output formatters for DevContext."""

import json
from typing import Any


def format_json(data: dict[str, Any], indent: int = 2) -> str:
    """Format context as JSON."""
    return json.dumps(data, indent=indent, ensure_ascii=False)


def format_markdown(data: dict[str, Any]) -> str:
    """Format context as readable Markdown."""
    lines = [
        "# 📊 Codebase Context",
        "",
        f"**Generated by DevContext v{data.get('version', '0.1.0')}**",
        "",
    ]
    
    # Project info
    if 'project' in data:
        proj = data['project']
        lines.extend([
            f"**Project:** {proj.get('name', 'Unknown')}",
            f"**Language:** {proj.get('language', 'Mixed')}",
            f"**Files:** {proj.get('file_count', 0)}",
            f"**Total size:** {proj.get('total_size', 0):,} bytes",
            "",
        ])
    
    # File tree
    if 'file_tree' in data:
        lines.extend(["## 📁 File Tree", ""])
        for node in data['file_tree'][:100]:  # Limit to 100 for readability
            indent = "  " * node.get('depth', 0)
            if node['type'] == 'dir':
                lines.append(f"{indent}📁 `{node['path']}/`")
            else:
                lines.append(f"{indent}📄 `{node['path']}`")
        
        if len(data['file_tree']) > 100:
            lines.append(f"\n_... and {len(data['file_tree']) - 100} more files_")
        lines.append("")
    
    # Key files
    if 'key_files' in data:
        lines.extend(["## 📌 Key Files", ""])
        for kf in data['key_files']:
            lines.extend([
                f"### `{kf['name']}`",
                "",
                f"```{kf.get('type', 'text')}",
                kf.get('preview', '')[:500],
                "```",
                "",
            ])
    
    # Code structure summary
    if 'structure' in data:
        struct = data['structure']
        if struct:
            lines.extend(["## 🏗️ Code Structure", ""])
            
            total_functions = sum(len(s.get('functions', [])) for s in struct.values())
            total_classes = sum(len(s.get('classes', [])) for s in struct.values())
            
            lines.extend([
                f"- **Total functions:** {total_functions}",
                f"- **Total classes/structs:** {total_classes}",
                "",
            ])
            
            # Show top files by function count
            by_functions = sorted(
                struct.items(),
                key=lambda x: len(x[1].get('functions', [])),
                reverse=True
            )[:5]
            
            if by_functions:
                lines.append("### Top files by function count")
                for path, info in by_functions:
                    fns = info.get('functions', [])
                    if fns:
                        lines.append(f"**{path}** — {len(fns)} functions")
                        for fn in fns[:5]:
                            lines.append(f"  - `{fn}()`")
                        if len(fns) > 5:
                            lines.append(f"  _... and {len(fns) - 5} more_")
                lines.append("")
    
    # Dependencies
    if 'dependencies' in data:
        deps = data['dependencies']
        if deps:
            lines.extend(["## 📦 Dependencies", ""])
            for dep in deps:
                lines.append(f"- `{dep}`")
            lines.append("")
    
    return "\n".join(lines)


def format_compact(data: dict[str, Any]) -> str:
    """Format context as compact single-file output for AI prompts."""
    lines = [
        "# CONTEXT",
        "",
        f"// Generated by DevContext v{data.get('version', '0.1.0')}",
        f"// Project: {data.get('project', {}).get('name', 'Unknown')}",
        f"// Files: {data.get('project', {}).get('file_count', 0)}",
        "",
        "## STRUCTURE",
    ]
    
    if 'file_tree' in data:
        for node in data['file_tree']:
            if node['type'] == 'dir':
                lines.append(f"  {node['path']}/")
            else:
                lines.append(f"  {node['path']}")
    
    if 'structure' in data:
        lines.append("")
        lines.append("## KEY ELEMENTS")
        for path, info in data['structure'].items():
            fns = info.get('functions', [])
            cls = info.get('classes', [])
            if fns or cls:
                lines.append(f"\n// {path}")
                for c in cls[:3]:
                    lines.append(f"  class {c}")
                for f in fns[:10]:
                    lines.append(f"  function {f}()")
    
    return "\n".join(lines)


def detect_language_from_path(path: str) -> str:
    """Guess language from file extension."""
    ext = path.lower().split('.')[-1]
    langs = {
        'py': 'Python', 'js': 'JavaScript', 'ts': 'TypeScript',
        'go': 'Go', 'rs': 'Rust', 'java': 'Java', 'rb': 'Ruby',
        'php': 'PHP', 'swift': 'Swift', 'kt': 'Kotlin',
        'c': 'C', 'cpp': 'C++', 'cs': 'C#', 'vue': 'Vue',
        'svelte': 'Svelte', 'html': 'HTML', 'css': 'CSS',
    }
    return langs.get(ext, ext.upper())