# Reporter module for generating analysis reports

import json
from datetime import datetime
from typing import Dict, Any, List, Optional
from collections import Counter


def generate_summary_report(context: Dict[str, Any]) -> str:
    """Generate a summary report from context."""
    lines = ["# Codebase Analysis Report", ""]
    lines.append(f"*Generated: {datetime.now().isoformat()}*")
    lines.append("")
    
    # File statistics
    files = context.get("files", {})
    meta = context.get("metadata", {})
    
    lines.append("## Overview")
    lines.append(f"- **Total Files:** {meta.get('total_files', len(files))}")
    lines.append(f"- **Languages:** {', '.join(meta.get('languages', []))}")
    lines.append(f"- **Total Functions:** {meta.get('total_functions', 0)}")
    lines.append(f"- **Total Classes:** {meta.get('total_classes', 0)}")
    lines.append("")
    
    # Language breakdown
    lang_counts = Counter()
    for info in files.values():
        if isinstance(info, dict) and info.get("language"):
            lang_counts[info["language"]] += 1
    
    if lang_counts:
        lines.append("## Language Distribution")
        for lang, count in lang_counts.most_common(10):
            pct = (count / len(files)) * 100
            bars = "█" * int(pct / 5)
            lines.append(f"{lang:15} {count:4} ({pct:5.1f}%) {bars}")
        lines.append("")
    
    # Complexity hotspots
    complex_files = []
    for path, info in files.items():
        if isinstance(info, dict):
            funcs = info.get("functions", [])
            classes = info.get("classes", [])
            if len(funcs) > 10 or len(classes) > 5:
                complex_files.append((path, len(funcs), len(classes)))
    
    if complex_files:
        lines.append("## Complexity Hotspots")
        lines.append("*Files with high function/class count:*")
        lines.append("")
        for path, funcs, classes in sorted(complex_files, key=lambda x: x[1] + x[2], reverse=True)[:10]:
            lines.append(f"- `{path}`: {funcs} functions, {classes} classes")
        lines.append("")
    
    # Recommendations
    lines.append("## Recommendations")
    
    if any(f.endswith(".py") for f in files):
        lines.append("- Consider adding type hints to Python files")
    
    if any(f.endswith((".ts", ".tsx")) for f in files):
        lines.append("- Enable strict TypeScript mode for better type safety")
    
    large_files = [(f, files[f]) for f in files if isinstance(files[f], dict) and files[f].get("lines", 0) > 500]
    if large_files:
        lines.append(f"- {len(large_files)} files exceed 500 lines - consider splitting")
    
    if not meta.get("has_tests"):
        lines.append("- No test files detected - add tests to improve reliability")
    
    lines.append("")
    lines.append("*Report generated by DevContext*")
    
    return "\n".join(lines)


def generate_health_report(context: Dict[str, Any]) -> Dict[str, Any]:
    """Generate a project health score."""
    score = 100
    issues = []
    suggestions = []
    
    files = context.get("files", {})
    meta = context.get("metadata", {})
    
    # Deduct for missing README
    if not any("readme" in f.lower() for f in files):
        score -= 10
        issues.append("No README.md found")
    
    # Deduct for missing tests
    if not any("test" in f.lower() for f in files):
        score -= 15
        issues.append("No test files detected")
    
    # Deduct for low documentation
    doc_files = [f for f in files if f.endswith((".md", ".rst", ".txt"))]
    if len(doc_files) < 2:
        score -= 5
        suggestions.append("Add more documentation files")
    
    # Deduct for large files
    large_files = 0
    for info in files.values():
        if isinstance(info, dict) and info.get("lines", 0) > 500:
            large_files += 1
    if large_files > 0:
        score -= large_files * 2
        issues.append(f"{large_files} files exceed 500 lines")
    
    return {
        "score": max(0, score),
        "grade": "A" if score >= 90 else "B" if score >= 80 else "C" if score >= 70 else "D" if score >= 60 else "F",
        "issues": issues,
        "suggestions": suggestions,
        "timestamp": datetime.now().isoformat()
    }


def generate_api_report(context: Dict[str, Any]) -> str:
    """Generate API endpoint report."""
    lines = ["# API Endpoints Report", ""]
    
    files = context.get("files", {})
    endpoints = []
    
    for path, info in files.items():
        if isinstance(info, dict):
            # Look for common API indicators
            exports = info.get("exports", [])
            functions = info.get("functions", [])
            
            for exp in exports:
                if any(word in exp.lower() for word in ["get", "post", "put", "delete", "patch", "route", "endpoint"]):
                    endpoints.append((path, exp))
            
            for func in functions:
                if any(word in func.lower() for word in ["get", "post", "put", "delete", "route"]):
                    endpoints.append((path, func))
    
    if endpoints:
        lines.append(f"## Found {len(endpoints)} potential API endpoints")
        lines.append("")
        
        current_file = None
        for path, endpoint in sorted(endpoints):
            if path != current_file:
                lines.append(f"### {path}")
                current_file = path
            lines.append(f"- `{endpoint}`")
            lines.append("")
    else:
        lines.append("*No API endpoints detected*")
        lines.append("")
    
    return "\n".join(lines)


def generate_dependencies_report(context: Dict[str, Any]) -> str:
    """Generate dependencies analysis report."""
    lines = ["# Dependencies Report", ""]
    
    files = context.get("files", {})
    imports = Counter()
    
    for path, info in files.items():
        if isinstance(info, dict):
            for imp in info.get("imports", []):
                # Extract package name
                pkg = imp.split(".")[0].split("/")[-1]
                imports[pkg] += 1
    
    if imports:
        lines.append(f"## {len(imports)} unique dependencies detected")
        lines.append("")
        lines.append("| Dependency | Usage Count |")
        lines.append("|------------|-------------|")
        for imp, count in imports.most_common(20):
            lines.append(f"| `{imp}` | {count} |")
        lines.append("")
    else:
        lines.append("*No imports detected*")
        lines.append("")
    
    return "\n".join(lines)


# CLI command
def main():
    import sys
    if len(sys.argv) < 2:
        print("Usage: reporter.py <context.json>")
        return 1
    
    with open(sys.argv[1]) as f:
        context = json.load(f)
    
    print(generate_summary_report(context))
    return 0


if __name__ == "__main__":
    exit(main() or 0)